### ISSUE TITLE
Create add/delete methods in every entity which have list fields

### ISSUE THREAD

**Issue by naslakboss** [CodeEnthusiasts/TrainingCenter#36]
Find in every entity fields List<?>
Check if they have add/remove methods inside.
If no, add it.

**Comment by SumaiyaSafdar** [comment]
hi, I want to work on the project can you suggest me ways to get started?

**Comment by AmeyaPhadnis-2019H1030012G** [comment]
Hi, I am new to the open-source community and looking forward to work on this Thanks in advance!

**Comment by naslakboss** [comment]
Sure, first of all : Check Wiki Section:
https://github.com/CodeEnthusiasts/TrainingCenter/wiki/Contribution-tutorial
Next, you can try to find graphs on slack(it is also avilable on READ.me)
Choose issue and pull request when finished (If you have no idea what to do - ask precisely about troubles)

**Comment by SumaiyaSafdar** [comment]
@naslakboss  Thank you very much for your response.. I'm really glad you responded.. I'm new to open source , can I contact you if I come across any query ??

**Comment by SumaiyaSafdar** [comment]
@AmeyaPhadnis-2019H1030012G  Hey I'm also new to this.. Can we get connected over LinkedIn so that we can help each other through it???

**Comment by naslakboss** [comment]
Sumaiya, you dont need to connect over Linkedin, just type here and ask precisely about troubles that you have. Here is updated version of guide
 [guide](https://github.com/CodeEnthusiasts/TrainingCenter/wiki/How-to-contribute%3F)

**Comment by SumaiyaSafdar** [comment]
the thing is.. I'm unable to get through the slack community.. They use some language different from english I'm unable to make out.. Please help

**Comment by naslakboss** [comment]
But you don't need to get through slack, just use guide
