### ISSUE TITLE
Create StrengthExercise Service (could be without tests to sunday evening)

### ISSUE THREAD

**Issue by naslakboss** [CodeEnthusiasts/TrainingCenter#43]
Create StrengthExerciseService with following methods: (SE = Strength Exercise)
CRUD (without return all SE)
Add posibility to add partial data (f.e only one field from details)
+addSEDetails
+removeSEDetails
+patchSEDEtails

**Comment by ciso112** [comment]
Hi, can you assign this to me?

**Comment by naslakboss** [comment]
I invited you. You need to accept invitation if you want to be assigned (otherwise, i can't) Anyway, you can start your works even without be assigned.
