### ISSUE TITLE
Change the packages structure in test directory

### ISSUE THREAD

**Issue by CcConStanTine** [CodeEnthusiasts/TrainingCenter#58]
Change the packages structure in test directory so it will be the same as in the main and move the existing test classes to appropriate packages.

**Comment by rubyAnneB** [comment]
I'll give this a try

**Comment by rubyAnneB** [comment]
would you mind giving me a few more details to work with?

**Comment by naslakboss** [comment]
There won't be so many test classes, so you can just divide as it follows:
constants(enum there)
services(abstract + implementations)
controllers(for integration tests)
