### ISSUE TITLE
Create possibility to add and remove images for given entities.

### ISSUE THREAD

**Issue by naslakboss** [CodeEnthusiasts/TrainingCenter#90]
Create funcionalities to add and remove images for given entities:
Movement
Muscle
You can use pattern from User, or create special interface for adding images

**Comment by pangeon** [comment]
I have read the instructions. I'll install the tools (Postman) and get to work. I will check informations about [Spring Profiles](https://dzone.com/articles/spring-boot-profiles-1?fbclid=IwAR2nHNU22Uj_T4hcb0vmXXOIeL9JDLZDt1qZEhV0vvxDPRiDVoxF7Vf1jrQ)
